# Vagrantfile
# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.image = "wonderchang/baseimage-ssh"
    d.has_ssh = true
  end
  config.ssh.password = 'vagrant'
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y nginx
    service nginx start
  SHELL
end
